### ISSUE TITLE
Option to define a search base for Active Directory

### ISSUE THREAD

**Issue by darkorion6661** [EvotecIT/CleanupMonster#13]
It would be good to be able to define a search base for Active Directory in order to limit the devices included for evaluation. Our organisation has a large and complex Active Directory and there is only a few areas that we would want to clean up.

We could potentially use the "-filter" which is sent to the Get-ADComputers command, but that command does also provide a -SearchBase parameter to. 

Perhaps adding a "-SearchBase" parameter to the script that can be also passed through to "Get-ADComputers -SearchBase"?

**Comment by PrzemyslawKlys** [comment]
Sure, it makes sense

**Comment by PrzemyslawKlys** [comment]
This has now been adressed

**Comment by darkorion6661** [comment]
Just saw that! Thank you so very much!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
