### ISSUE TITLE
Error getting computer from Intune

### ISSUE THREAD

**Issue by thenamelessthing** [EvotecIT/CleanupMonster#15]
Hello, i'm trying to use the script but I got this error when I run it:

![image](https://github.com/user-attachments/assets/86e1f7f1-9ffc-4119-a9c1-4f8d452926eb)

If I run the following command manually, I can see all computer. But If I run the script no. 

- Get-MyDevice -Synchronized

Any idea?

**Comment by PrzemyslawKlys** [comment]
Check if the graph modules have only one version. If you have more than one, delete those. They get in conflicts. The problem is probably with microsoft identity dll as lots of modules use it and get in conflicts on different version.
