### ISSUE TITLE
Search Base use?

### ISSUE THREAD

**Issue by thenamelessthing** [EvotecIT/CleanupMonster#16]
Hi, I want to thank you so much for this great tool. I had already dreamed of a tool like this...

I am in the process of familiarizing myself with the tool and with a view to automating using a config file (based on one of those suggested on the blog). How can I use the search base option to process only the computers contained in an OU?

Thanks

P.S. What do you think about extending the scope to perform DHCP/DNS cleaning of these devices at the same time?

**Comment by PrzemyslawKlys** [comment]
There is already a search base parameter which takes a string or hashtable domain = searchbase. You can also use Filter which is applicable similar way. You can exclude OUs using Exclusions and using wildcards. 

I guess I could also copy solution from [PasswordSolution ](https://github.com/EvotecIT/PasswordSolution) project, where it allows to define searchbase, but also do filtering on OU within that. 

As for your PS, sure this module is supposed to grow to other scopes but one would first need to define what sort of criteria it needs to apply. There should also be one for users/service accounts/msa/gmsa, or maybe even groups, but first someone would need to sit down and define exactly what would work and how to prevent breaking AD ;)

**Comment by PrzemyslawKlys** [comment]
Here's actually release that added this:
- https://github.com/EvotecIT/CleanupMonster/releases/tag/v2.8.6

**Comment by thenamelessthing** [comment]
Sorry for the silly question, but am I doing the right thing by specifying the parameter this way?

![image](https://github.com/user-attachments/assets/4e9b3366-dca9-4faf-a125-908cf8a90fee)

Thank you!

**Comment by PrzemyslawKlys** [comment]
Yes, should work
