### ISSUE TITLE
Running script with mixed account

### ISSUE THREAD

**Issue by thenamelessthing** [EvotecIT/CleanupMonster#17]
Let me explain, I'm trying to use the script to clean up our On-Prem AD and validate the activity with Intune as well. I run the script with an On-Prem admin account. Then Graph authentication is performed with another account, because my On-Prem admin account doesn't have access to resources in Azure. When I display the HTML report, I get Access denied in the “Action comment” column. I guess it's trying to perform the actions with the account used for Graph?

**Comment by PrzemyslawKlys** [comment]
Graph account is used only to get data. You either lack permission on your onprem account or on the object is protected from accidental deletion.

**Comment by thenamelessthing** [comment]
I think I've found it. Another thing I find strange, for many I have these actions in duplicate. One with access denied and one with success. Any idea?

![image](https://github.com/user-attachments/assets/499bdca8-6d8b-47c8-9a8c-4327fec9313b)

**Comment by PrzemyslawKlys** [comment]
If it's in the "history" tab, that means you run it twice - once it tried to delete it and failed, the other time it succeeded.

**Comment by thenamelessthing** [comment]
well I'm making progress, a beginner's mistake. Having defined my searchbase in a specific OU. I shouldn't specify an OU where to move computers that are outside the searchbase...
