### ISSUE TITLE
Duplicated machines in "to disable" and "to delete"

### ISSUE THREAD

**Issue by red-erik** [EvotecIT/CleanupMonster#4]
Hello,
when exporting data to excel, I have a lot of duplicated machines, present in both "to disable" and into "to delete".
Would it be possible to have the "to delete" list not containing any from "to disable"?
Probably I'm doing something wrong.

Regards,
Red.

**Comment by PrzemyslawKlys** [comment]
I've changed the logic in newest version. When you set settings for both Disable and Delete and they both match they would usually go thru the process of Disabling and then Deleting in the same run. In new version I've changed that logic so Delete overwrites Disable. 

There is one bug where it will display in new version Actions to be taken +1 to actual actions. I am not yet sure where it's coming from, but I guess there's some null there.

**Comment by red-erik** [comment]
Than you.
I'm testing the latest version. Do you think it would be possible to have the Forest as a parameter ? Something like
"$Forest = Get-ADForest"     -->     "$Forest = Get-ADForest $Forest"
It will help in complex env when you connect and run code with account from a Trusted (ESAE) forest.

Regards,
Red.

**Comment by PrzemyslawKlys** [comment]
Ye, I should probably expose forest/domains, but i guess then also credentials is required no?

**Comment by PrzemyslawKlys** [comment]
IT shoudl now allow Forest/IncludeDomains/ExcludeDomains in 1.6.0

**Comment by red-erik** [comment]
Thank you very much. I'm starting all test now.
In case of "trusted forest" the account is already logged so "credentials" should not be required.

Regards,
Red.
