### ISSUE TITLE
Feature Request: Exclude special objects

### ISSUE THREAD

**Issue by red-erik** [EvotecIT/CleanupMonster#7]
Hello,
usually, one of the topics to consider with AD CleanUp is to be sure not to delete "special" objects like ClusterNames since, if the cluster is never switching, the LastLogonTimestamp attribute is not updated ( updated only when the Network Name is brought online).
In powershell, you can use something like that:

Get-ADComputer -Filter 'servicePrincipalName -NotLike "*MSClusterVirtualServer*"' -SearchBase “DC=domain,DC=com” -Properties Name, LastLogonTimestamp, pwdLastSet, servicePrincipalName -ResultPageSize 0 | Select Name, @{n='LastLogonTimestamp';e={[DateTime]::FromFileTime($_.LastLogonTimestamp)}}, @{n='pwdLastSet';e={[DateTime]::FromFileTime($_.pwdLastSet)}}, DistinguishedName

Regards,
Red

Credits to:
[https://richardjgreen.net/cleaning-up-active-directory-cluster-computer-accounts/](https://github.com/healthchecks/healthchecks/issues/url)

**Comment by red-erik** [comment]
Hello,
unfortunately not, since:

- not all clusters are in the same OU but spread all over AD
- not only clusters have SPN defined
- not all cluster have a strict "naming convention" to exclude them by name

I understand this a problem of mine but another exclusion for  "servicePrincipalName" would help, probably not only myself,
but I understand your point.
I can always work on Excel export and than apply a filter

Regards,
Red.

**Comment by PrzemyslawKlys** [comment]
I understand. It makes sense to add filtering on SPN as well. 

> Hello, unfortunately not, since:
> 
> * not all clusters are in the same OU but spread all over AD
> * not only clusters have SPN defined

The code you proposed specifically filters out MSClusterVirtualServer SPN - so if the cluster doesn't have it defined - the exclusion I will create will not really work. 

> * not all cluster have a strict "naming convention" to exclude them by name
> 
> I understand this a problem of mine but another exclusion for "servicePrincipalName" would help, probably not only myself, but I understand your point. I can always work on Excel export and than apply a filter
> 
> Regards, Red.

I would also assume MSCluster doesn't have Windows Server 2016 or similar as operating system no?

Przemek
